"use client";

import React from "react";
import { format } from "date-fns";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Sparkles, X, Target, MessageSquare, ShieldCheck, Activity, CheckCircle2, ArrowUpRight, Lightbulb } from "lucide-react";

interface InterviewReportDialogProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    interview: any | null;
}

export function InterviewReportDialog({ open, onOpenChange, interview }: InterviewReportDialogProps) {
    if (!interview) return null;

    const isFailed = interview.status === "FAILED";
    const overallScore =
        interview.technicalScore !== null && interview.communicationScore !== null && interview.confidenceScore !== null
            ? Math.round((interview.technicalScore + interview.communicationScore + interview.confidenceScore) / 3)
            : "--";

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="w-[95vw] max-w-4xl max-h-[90vh] bg-[#050505] overflow-y-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:'none'] [scrollbar-width:'none'] border border-white/5 p-0 shadow-[0_0_80px_-20px_rgba(var(--color-primary),0.2)] rounded-[2rem] gap-0 outline-none">
                <DialogDescription className="sr-only">Detailed interview report results</DialogDescription>

                {/* Background ambient light */}
                <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(var(--color-primary),0.05),transparent_70%)] pointer-events-none -z-10" />

                <div className="p-8 md:p-12 space-y-10">
                    {/* Header Section */}
                    <div className="flex flex-col md:flex-row md:items-start justify-between gap-6 border-b border-white/5 pb-10 relative">
                        {/* Decorative glow line */}
                        <div className="absolute bottom-0 inset-x-0 h-px bg-gradient-to-r from-transparent via-primary/30 to-transparent" />

                        <div className="space-y-4 max-w-xl">
                            <div className="flex flex-wrap items-center gap-3">
                                <div className={`px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-widest flex items-center gap-2 ${interview.status === 'COMPLETED' ? 'bg-emerald-500/10 text-emerald-500 border border-emerald-500/20' : 'bg-red-500/10 text-red-500 border border-red-500/20'}`}>
                                    <span className="h-1.5 w-1.5 rounded-full bg-current shadow-[0_0_8px_currentColor]"></span>
                                    {interview.status}
                                </div>
                                <div className="px-3 py-1 rounded-full text-[10px] font-bold text-white/60 bg-white/5 border border-white/10">
                                    {format(new Date(interview.createdAt), "MMMM dd, yyyy")}
                                </div>
                                <div className="px-3 py-1 rounded-full text-[10px] font-bold text-white/60 bg-white/5 border border-white/10 flex items-center gap-1.5">
                                    <Sparkles className="h-3 w-3" />
                                    {interview.language}
                                </div>
                            </div>

                            <DialogTitle className="text-4xl md:text-5xl font-black text-white tracking-tighter leading-tight bg-clip-text text-transparent bg-gradient-to-br from-white to-white/60">
                                {interview.targetRole}
                            </DialogTitle>

                            <p className="text-white/40 font-medium text-sm">
                                Comprehensive analysis generated by Senpai Simulation Engine.
                            </p>
                        </div>

                        {/* Huge Overall Score Pill */}
                        <div className="flex flex-col items-center justify-center p-6 bg-primary/5 border border-primary/20 rounded-3xl shrink-0 shadow-[0_0_40px_-10px_rgba(var(--color-primary),0.1)]">
                            <span className="text-primary/60 text-[10px] uppercase tracking-[0.2em] font-bold mb-1">Overall Performance</span>
                            <div className="flex items-baseline gap-1">
                                <span className="text-7xl font-black text-white tracking-tighter drop-shadow-sm">{overallScore}</span>
                                <span className="text-xl font-bold text-primary/40">/100</span>
                            </div>
                        </div>
                    </div>

                    {/* Metrics Grid */}
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                        {/* Technical */}
                        <div className="p-6 bg-gradient-to-b from-[#111] to-[#0a0a0a] rounded-[2rem] border border-white/5 flex flex-col items-center text-center relative overflow-hidden group hover:border-blue-500/30 transition-colors">
                            <div className="absolute inset-0 bg-blue-500/5 opacity-0 group-hover:opacity-100 transition-opacity" />
                            <div className="h-12 w-12 rounded-full bg-blue-500/10 text-blue-500 flex items-center justify-center mb-4">
                                <Target className="h-6 w-6" />
                            </div>
                            <span className="text-[10px] font-bold text-white/50 uppercase tracking-widest mb-1">Technical Skills</span>
                            <span className="text-4xl font-black text-white">{interview.technicalScore !== null ? Math.round(interview.technicalScore) : "--"}</span>
                        </div>

                        {/* Communication */}
                        <div className="p-6 bg-gradient-to-b from-[#111] to-[#0a0a0a] rounded-[2rem] border border-white/5 flex flex-col items-center text-center relative overflow-hidden group hover:border-purple-500/30 transition-colors">
                            <div className="absolute inset-0 bg-purple-500/5 opacity-0 group-hover:opacity-100 transition-opacity" />
                            <div className="h-12 w-12 rounded-full bg-purple-500/10 text-purple-500 flex items-center justify-center mb-4">
                                <MessageSquare className="h-6 w-6" />
                            </div>
                            <span className="text-[10px] font-bold text-white/50 uppercase tracking-widest mb-1">Communication</span>
                            <span className="text-4xl font-black text-white">{interview.communicationScore !== null ? Math.round(interview.communicationScore) : "--"}</span>
                        </div>

                        {/* Confidence */}
                        <div className="p-6 bg-gradient-to-b from-[#111] to-[#0a0a0a] rounded-[2rem] border border-white/5 flex flex-col items-center text-center relative overflow-hidden group hover:border-emerald-500/30 transition-colors">
                            <div className="absolute inset-0 bg-emerald-500/5 opacity-0 group-hover:opacity-100 transition-opacity" />
                            <div className="h-12 w-12 rounded-full bg-emerald-500/10 text-emerald-500 flex items-center justify-center mb-4">
                                <ShieldCheck className="h-6 w-6" />
                            </div>
                            <span className="text-[10px] font-bold text-white/50 uppercase tracking-widest mb-1">Confidence</span>
                            <span className="text-4xl font-black text-white">{interview.confidenceScore !== null ? Math.round(interview.confidenceScore) : "--"}</span>
                        </div>
                    </div>

                    {/* Detailed AI Feedback Box (Replaced with 3 structured lists) */}
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                        {/* Strengths */}
                        <div className="relative p-6 rounded-[2rem] bg-gradient-to-b from-emerald-500/5 to-transparent border border-emerald-500/10 overflow-hidden group hover:border-emerald-500/30 transition-all">
                            <div className="flex items-center gap-3 mb-6 pb-4 border-b border-white/5">
                                <div className="p-2 rounded-xl bg-emerald-500/10 text-emerald-500">
                                    <CheckCircle2 className="h-5 w-5" />
                                </div>
                                <h3 className="text-lg font-bold text-white tracking-tight">Key Strengths</h3>
                            </div>
                            <ul className="space-y-4">
                                {Array.isArray(interview.strengths) && interview.strengths.length > 0 ? (
                                    interview.strengths.map((point: string, i: number) => (
                                        <li key={i} className="flex items-start gap-3 text-sm text-white/70 font-medium leading-relaxed">
                                            <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 mt-1.5 shrink-0 shadow-[0_0_8px_#10b981]" />
                                            <span>{point}</span>
                                        </li>
                                    ))
                                ) : (
                                    <p className="text-sm text-white/30 italic">No specific strengths recorded.</p>
                                )}
                            </ul>
                        </div>

                        {/* Improvements */}
                        <div className="relative p-6 rounded-[2rem] bg-gradient-to-b from-red-500/5 to-transparent border border-red-500/10 overflow-hidden group hover:border-red-500/30 transition-all">
                            <div className="flex items-center gap-3 mb-6 pb-4 border-b border-white/5">
                                <div className="p-2 rounded-xl bg-red-500/10 text-red-500">
                                    <ArrowUpRight className="h-5 w-5" />
                                </div>
                                <h3 className="text-lg font-bold text-white tracking-tight">Areas to Improve</h3>
                            </div>
                            <ul className="space-y-4">
                                {Array.isArray(interview.improvements) && interview.improvements.length > 0 ? (
                                    interview.improvements.map((point: string, i: number) => (
                                        <li key={i} className="flex items-start gap-3 text-sm text-white/70 font-medium leading-relaxed">
                                            <span className="w-1.5 h-1.5 rounded-full bg-red-500 mt-1.5 shrink-0 shadow-[0_0_8px_#ef4444]" />
                                            <span>{point}</span>
                                        </li>
                                    ))
                                ) : (
                                    <p className="text-sm text-white/30 italic">No specific improvements recorded.</p>
                                )}
                            </ul>
                        </div>

                        {/* Key Points */}
                        <div className="relative p-6 rounded-[2rem] bg-gradient-to-b from-blue-500/5 to-transparent border border-blue-500/10 overflow-hidden group hover:border-blue-500/30 transition-all">
                            <div className="flex items-center gap-3 mb-6 pb-4 border-b border-white/5">
                                <div className="p-2 rounded-xl bg-blue-500/10 text-blue-500">
                                    <Lightbulb className="h-5 w-5" />
                                </div>
                                <h3 className="text-lg font-bold text-white tracking-tight">Key Takeaways</h3>
                            </div>
                            <ul className="space-y-4">
                                {Array.isArray(interview.keyPoints) && interview.keyPoints.length > 0 ? (
                                    interview.keyPoints.map((point: string, i: number) => (
                                        <li key={i} className="flex items-start gap-3 text-sm text-white/70 font-medium leading-relaxed">
                                            <span className="w-1.5 h-1.5 rounded-full bg-blue-500 mt-1.5 shrink-0 shadow-[0_0_8px_#3b82f6]" />
                                            <span>{point}</span>
                                        </li>
                                    ))
                                ) : (
                                    <p className="text-sm text-white/30 italic">No key takeaways generated yet.</p>
                                )}
                            </ul>
                        </div>
                    </div>

                    {/* Footer Area */}
                    <div className="pt-4 flex items-center justify-between text-xs text-white/30 font-medium">
                        <span>Report ID: {interview.id.substring(0, 8)}...</span>
                        <span>Generated securely. Keep confidential.</span>
                    </div>

                </div>
            </DialogContent>
        </Dialog>
    );
}
